apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all of the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: "Run unit tests using Nose."
  workspaces:
    - name: source  # 🔹 Se agrega el workspace para acceder a los archivos
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"

  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)  # 🔹 Se asegura de ejecutar en el workspace
      script: |
        #!/bin/bash
        set -e
        echo "Installing dependencies..."
        python -m pip install --upgrade pip wheel
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "⚠️ WARNING: requirements.txt not found, skipping dependency installation."
        fi

        echo "Running nosetests..."
        nosetests $(params.args)
